spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      password: disabled  # default security 비밀번호 끔

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080

