spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db?serverTimezone=Asia/Seoul
    username: root
    password: 0000

jwt:
  secret: ThisIsASecretKeyForJWTGeneration123456

server:
  port: 8080
